# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHPANEL_ONEPLUS)	+= touchpanel_common_driver.o
obj-$(CONFIG_TOUCHPANEL_SAMSUNG)	+= samsung/
obj-$(CONFIG_TOUCHPANEL_SYNAPTICS)	+= synaptics/
